apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-webapp
  template:
    metadata:
      labels:
        app: flask-webapp
    spec:
      containers:
        - name: flask-webapp
          image: docker.io/payalkharat/flask_webapp_payal:v2
          ports:
            - containerPort: 8080
